FROM apache/airflow:2.7.0

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

USER airflow
RUN pip install --no-cache-dir dbt-core==1.7.14 dbt-postgres==1.7.14
