FROM apache/airflow:2.9.3-python3.12

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

USER airflow
COPY requirements.airflow.txt /tmp/requirements.airflow.txt
RUN pip install --no-cache-dir -r /tmp/requirements.airflow.txt
RUN pip install --no-cache-dir dbt-core==1.7.14 dbt-postgres==1.7.14
